from config.database import db

# Уровень 1 - 300 слов
level_1_words = [
    # Основные глаголы (80 слов)
    {"word": "be", "translation": "быть", "level": 1},
    {"word": "have", "translation": "иметь", "level": 1},
    {"word": "do", "translation": "делать", "level": 1},
    {"word": "go", "translation": "идти", "level": 1},
    {"word": "get", "translation": "получать", "level": 1},
    {"word": "make", "translation": "делать", "level": 1},
    {"word": "know", "translation": "знать", "level": 1},
    {"word": "think", "translation": "думать", "level": 1},
    {"word": "take", "translation": "брать", "level": 1},
    {"word": "see", "translation": "видеть", "level": 1},
    {"word": "come", "translation": "приходить", "level": 1},
    {"word": "want", "translation": "хотеть", "level": 1},
    {"word": "look", "translation": "смотреть", "level": 1},
    {"word": "use", "translation": "использовать", "level": 1},
    {"word": "find", "translation": "находить", "level": 1},
    {"word": "give", "translation": "давать", "level": 1},
    {"word": "tell", "translation": "рассказывать", "level": 1},
    {"word": "work", "translation": "работать", "level": 1},
    {"word": "call", "translation": "звонить", "level": 1},
    {"word": "try", "translation": "пытаться", "level": 1},
    {"word": "ask", "translation": "спрашивать", "level": 1},
    {"word": "need", "translation": "нуждаться", "level": 1},
    {"word": "feel", "translation": "чувствовать", "level": 1},
    {"word": "become", "translation": "становиться", "level": 1},
    {"word": "leave", "translation": "уходить", "level": 1},
    {"word": "put", "translation": "класть", "level": 1},
    {"word": "mean", "translation": "значить", "level": 1},
    {"word": "keep", "translation": "хранить", "level": 1},
    {"word": "let", "translation": "позволять", "level": 1},
    {"word": "begin", "translation": "начинать", "level": 1},
    {"word": "seem", "translation": "казаться", "level": 1},
    {"word": "help", "translation": "помогать", "level": 1},
    {"word": "talk", "translation": "разговаривать", "level": 1},
    {"word": "turn", "translation": "поворачивать", "level": 1},
    {"word": "start", "translation": "начинать", "level": 1},
    {"word": "show", "translation": "показывать", "level": 1},
    {"word": "hear", "translation": "слышать", "level": 1},
    {"word": "play", "translation": "играть", "level": 1},
    {"word": "run", "translation": "бежать", "level": 1},
    {"word": "move", "translation": "двигаться", "level": 1},
    {"word": "like", "translation": "нравиться", "level": 1},
    {"word": "live", "translation": "жить", "level": 1},
    {"word": "believe", "translation": "верить", "level": 1},
    {"word": "hold", "translation": "держать", "level": 1},
    {"word": "bring", "translation": "приносить", "level": 1},
    {"word": "happen", "translation": "случаться", "level": 1},
    {"word": "write", "translation": "писать", "level": 1},
    {"word": "provide", "translation": "обеспечивать", "level": 1},
    {"word": "sit", "translation": "сидеть", "level": 1},
    {"word": "stand", "translation": "стоять", "level": 1},
    {"word": "lose", "translation": "терять", "level": 1},
    {"word": "pay", "translation": "платить", "level": 1},
    {"word": "meet", "translation": "встречать", "level": 1},
    {"word": "include", "translation": "включать", "level": 1},
    {"word": "continue", "translation": "продолжать", "level": 1},
    {"word": "set", "translation": "устанавливать", "level": 1},
    {"word": "learn", "translation": "учить", "level": 1},
    {"word": "change", "translation": "менять", "level": 1},
    {"word": "lead", "translation": "вести", "level": 1},
    {"word": "understand", "translation": "понимать", "level": 1},
    {"word": "watch", "translation": "смотреть", "level": 1},
    {"word": "follow", "translation": "следовать", "level": 1},
    {"word": "stop", "translation": "останавливать", "level": 1},
    {"word": "create", "translation": "создавать", "level": 1},
    {"word": "speak", "translation": "говорить", "level": 1},
    {"word": "read", "translation": "читать", "level": 1},
    {"word": "allow", "translation": "позволять", "level": 1},
    {"word": "add", "translation": "добавлять", "level": 1},
    {"word": "spend", "translation": "тратить", "level": 1},
    {"word": "grow", "translation": "расти", "level": 1},
    {"word": "open", "translation": "открывать", "level": 1},
    {"word": "walk", "translation": "ходить", "level": 1},
    {"word": "win", "translation": "выигрывать", "level": 1},
    {"word": "offer", "translation": "предлагать", "level": 1},
    {"word": "remember", "translation": "помнить", "level": 1},
    {"word": "love", "translation": "любить", "level": 1},
    {"word": "consider", "translation": "рассматривать", "level": 1},
    {"word": "appear", "translation": "появляться", "level": 1},
    {"word": "buy", "translation": "покупать", "level": 1},
    {"word": "wait", "translation": "ждать", "level": 1},
    {"word": "serve", "translation": "служить", "level": 1},
    {"word": "die", "translation": "умирать", "level": 1},
    {"word": "send", "translation": "отправлять", "level": 1},
    
    # Существительные - люди и семья (40 слов)
    {"word": "person", "translation": "человек", "level": 1},
    {"word": "man", "translation": "мужчина", "level": 1},
    {"word": "woman", "translation": "женщина", "level": 1},
    {"word": "child", "translation": "ребенок", "level": 1},
    {"word": "family", "translation": "семья", "level": 1},
    {"word": "friend", "translation": "друг", "level": 1},
    {"word": "people", "translation": "люди", "level": 1},
    {"word": "mother", "translation": "мать", "level": 1},
    {"word": "father", "translation": "отец", "level": 1},
    {"word": "son", "translation": "сын", "level": 1},
    {"word": "daughter", "translation": "дочь", "level": 1},
    {"word": "brother", "translation": "брат", "level": 1},
    {"word": "sister", "translation": "сестра", "level": 1},
    {"word": "parent", "translation": "родитель", "level": 1},
    {"word": "husband", "translation": "муж", "level": 1},
    {"word": "wife", "translation": "жена", "level": 1},
    {"word": "boy", "translation": "мальчик", "level": 1},
    {"word": "girl", "translation": "девочка", "level": 1},
    {"word": "baby", "translation": "младенец", "level": 1},
    {"word": "grandmother", "translation": "бабушка", "level": 1},
    {"word": "grandfather", "translation": "дедушка", "level": 1},
    {"word": "uncle", "translation": "дядя", "level": 1},
    {"word": "aunt", "translation": "тетя", "level": 1},
    {"word": "cousin", "translation": "двоюродный брат/сестра", "level": 1},
    {"word": "student", "translation": "студент", "level": 1},
    {"word": "teacher", "translation": "учитель", "level": 1},
    {"word": "doctor", "translation": "врач", "level": 1},
    {"word": "worker", "translation": "работник", "level": 1},
    {"word": "customer", "translation": "клиент", "level": 1},
    {"word": "neighbor", "translation": "сосед", "level": 1},
    {"word": "guest", "translation": "гость", "level": 1},
    {"word": "human", "translation": "человек", "level": 1},
    {"word": "adult", "translation": "взрослый", "level": 1},
    {"word": "teenager", "translation": "подросток", "level": 1},
    {"word": "couple", "translation": "пара", "level": 1},
    {"word": "group", "translation": "группа", "level": 1},
    {"word": "team", "translation": "команда", "level": 1},
    {"word": "community", "translation": "сообщество", "level": 1},
    {"word": "population", "translation": "население", "level": 1},
    
    # Существительные - места и природа (50 слов)
    {"word": "home", "translation": "дом", "level": 1},
    {"word": "school", "translation": "школа", "level": 1},
    {"word": "work", "translation": "работа", "level": 1},
    {"word": "city", "translation": "город", "level": 1},
    {"word": "country", "translation": "страна", "level": 1},
    {"word": "world", "translation": "мир", "level": 1},
    {"word": "house", "translation": "дом", "level": 1},
    {"word": "room", "translation": "комната", "level": 1},
    {"word": "street", "translation": "улица", "level": 1},
    {"word": "park", "translation": "парк", "level": 1},
    {"word": "building", "translation": "здание", "level": 1},
    {"word": "garden", "translation": "сад", "level": 1},
    {"word": "place", "translation": "место", "level": 1},
    {"word": "area", "translation": "область", "level": 1},
    {"word": "town", "translation": "городок", "level": 1},
    {"word": "village", "translation": "деревня", "level": 1},
    {"word": "shop", "translation": "магазин", "level": 1},
    {"word": "restaurant", "translation": "ресторан", "level": 1},
    {"word": "hotel", "translation": "отель", "level": 1},
    {"word": "hospital", "translation": "больница", "level": 1},
    {"word": "bank", "translation": "банк", "level": 1},
    {"word": "airport", "translation": "аэропорт", "level": 1},
    {"word": "station", "translation": "станция", "level": 1},
    {"word": "university", "translation": "университет", "level": 1},
    {"word": "office", "translation": "офис", "level": 1},
    {"word": "company", "translation": "компания", "level": 1},
    {"word": "market", "translation": "рынок", "level": 1},
    {"word": "beach", "translation": "пляж", "level": 1},
    {"word": "mountain", "translation": "гора", "level": 1},
    {"word": "river", "translation": "река", "level": 1},
    {"word": "lake", "translation": "озеро", "level": 1},
    {"word": "sea", "translation": "море", "level": 1},
    {"word": "forest", "translation": "лес", "level": 1},
    {"word": "field", "translation": "поле", "level": 1},
    {"word": "sky", "translation": "небо", "level": 1},
    {"word": "sun", "translation": "солнце", "level": 1},
    {"word": "moon", "translation": "луна", "level": 1},
    {"word": "star", "translation": "звезда", "level": 1},
    {"word": "earth", "translation": "земля", "level": 1},
    {"word": "tree", "translation": "дерево", "level": 1},
    {"word": "flower", "translation": "цветок", "level": 1},
    {"word": "animal", "translation": "животное", "level": 1},
    {"word": "bird", "translation": "птица", "level": 1},
    {"word": "dog", "translation": "собака", "level": 1},
    {"word": "cat", "translation": "кот", "level": 1},
    {"word": "water", "translation": "вода", "level": 1},
    {"word": "fire", "translation": "огонь", "level": 1},
    {"word": "air", "translation": "воздух", "level": 1},
    {"word": "land", "translation": "земля", "level": 1},
    
    # Существительные - еда и напитки (40 слов)
    {"word": "water", "translation": "вода", "level": 1},
    {"word": "food", "translation": "еда", "level": 1},
    {"word": "apple", "translation": "яблоко", "level": 1},
    {"word": "bread", "translation": "хлеб", "level": 1},
    {"word": "milk", "translation": "молоко", "level": 1},
    {"word": "tea", "translation": "чай", "level": 1},
    {"word": "coffee", "translation": "кофе", "level": 1},
    {"word": "meat", "translation": "мясо", "level": 1},
    {"word": "fish", "translation": "рыба", "level": 1},
    {"word": "fruit", "translation": "фрукт", "level": 1},
    {"word": "vegetable", "translation": "овощ", "level": 1},
    {"word": "rice", "translation": "рис", "level": 1},
    {"word": "egg", "translation": "яйцо", "level": 1},
    {"word": "cheese", "translation": "сыр", "level": 1},
    {"word": "butter", "translation": "масло", "level": 1},
    {"word": "salt", "translation": "соль", "level": 1},
    {"word": "sugar", "translation": "сахар", "level": 1},
    {"word": "chicken", "translation": "курица", "level": 1},
    {"word": "beef", "translation": "говядина", "level": 1},
    {"word": "pork", "translation": "свинина", "level": 1},
    {"word": "potato", "translation": "картофель", "level": 1},
    {"word": "tomato", "translation": "помидор", "level": 1},
    {"word": "carrot", "translation": "морковь", "level": 1},
    {"word": "onion", "translation": "лук", "level": 1},
    {"word": "banana", "translation": "банан", "level": 1},
    {"word": "orange", "translation": "апельсин", "level": 1},
    {"word": "juice", "translation": "сок", "level": 1},
    {"word": "wine", "translation": "вино", "level": 1},
    {"word": "beer", "translation": "пиво", "level": 1},
    {"word": "cake", "translation": "торт", "level": 1},
    {"word": "chocolate", "translation": "шоколад", "level": 1},
    {"word": "ice cream", "translation": "мороженое", "level": 1},
    {"word": "soup", "translation": "суп", "level": 1},
    {"word": "salad", "translation": "салат", "level": 1},
    {"word": "sandwich", "translation": "бутерброд", "level": 1},
    {"word": "pizza", "translation": "пицца", "level": 1},
    {"word": "pasta", "translation": "паста", "level": 1},
    {"word": "breakfast", "translation": "завтрак", "level": 1},
    {"word": "lunch", "translation": "обед", "level": 1},
    {"word": "dinner", "translation": "ужин", "level": 1},
    
    # Прилагательные (50 слов)
    {"word": "good", "translation": "хороший", "level": 1},
    {"word": "bad", "translation": "плохой", "level": 1},
    {"word": "big", "translation": "большой", "level": 1},
    {"word": "small", "translation": "маленький", "level": 1},
    {"word": "new", "translation": "новый", "level": 1},
    {"word": "old", "translation": "старый", "level": 1},
    {"word": "young", "translation": "молодой", "level": 1},
    {"word": "hot", "translation": "горячий", "level": 1},
    {"word": "cold", "translation": "холодный", "level": 1},
    {"word": "happy", "translation": "счастливый", "level": 1},
    {"word": "sad", "translation": "грустный", "level": 1},
    {"word": "beautiful", "translation": "красивый", "level": 1},
    {"word": "ugly", "translation": "уродливый", "level": 1},
    {"word": "rich", "translation": "богатый", "level": 1},
    {"word": "poor", "translation": "бедный", "level": 1},
    {"word": "strong", "translation": "сильный", "level": 1},
    {"word": "weak", "translation": "слабый", "level": 1},
    {"word": "clean", "translation": "чистый", "level": 1},
    {"word": "dirty", "translation": "грязный", "level": 1},
    {"word": "easy", "translation": "легкий", "level": 1},
    {"word": "difficult", "translation": "трудный", "level": 1},
    {"word": "expensive", "translation": "дорогой", "level": 1},
    {"word": "cheap", "translation": "дешевый", "level": 1},
    {"word": "fast", "translation": "быстрый", "level": 1},
    {"word": "slow", "translation": "медленный", "level": 1},
    {"word": "high", "translation": "высокий", "level": 1},
    {"word": "low", "translation": "низкий", "level": 1},
    {"word": "long", "translation": "длинный", "level": 1},
    {"word": "short", "translation": "короткий", "level": 1},
    {"word": "heavy", "translation": "тяжелый", "level": 1},
    {"word": "light", "translation": "легкий", "level": 1},
    {"word": "dark", "translation": "темный", "level": 1},
    {"word": "bright", "translation": "яркий", "level": 1},
    {"word": "soft", "translation": "мягкий", "level": 1},
    {"word": "hard", "translation": "твердый", "level": 1},
    {"word": "sweet", "translation": "сладкий", "level": 1},
    {"word": "sour", "translation": "кислый", "level": 1},
    {"word": "fresh", "translation": "свежий", "level": 1},
    {"word": "tired", "translation": "уставший", "level": 1},
    {"word": "hungry", "translation": "голодный", "level": 1},
    {"word": "thirsty", "translation": "жаждущий", "level": 1},
    {"word": "full", "translation": "полный", "level": 1},
    {"word": "empty", "translation": "пустой", "level": 1},
    {"word": "right", "translation": "правильный", "level": 1},
    {"word": "wrong", "translation": "неправильный", "level": 1},
    {"word": "true", "translation": "истинный", "level": 1},
    {"word": "false", "translation": "ложный", "level": 1},
    {"word": "free", "translation": "свободный", "level": 1},
    {"word": "busy", "translation": "занятый", "level": 1},
    
    # Дни, время, числа (40 слов)
    {"word": "time", "translation": "время", "level": 1},
    {"word": "day", "translation": "день", "level": 1},
    {"word": "week", "translation": "неделя", "level": 1},
    {"word": "month", "translation": "месяц", "level": 1},
    {"word": "year", "translation": "год", "level": 1},
    {"word": "today", "translation": "сегодня", "level": 1},
    {"word": "tomorrow", "translation": "завтра", "level": 1},
    {"word": "yesterday", "translation": "вчера", "level": 1},
    {"word": "morning", "translation": "утро", "level": 1},
    {"word": "evening", "translation": "вечер", "level": 1},
    {"word": "night", "translation": "ночь", "level": 1},
    {"word": "hour", "translation": "час", "level": 1},
    {"word": "minute", "translation": "минута", "level": 1},
    {"word": "second", "translation": "секунда", "level": 1},
    {"word": "Monday", "translation": "понедельник", "level": 1},
    {"word": "Tuesday", "translation": "вторник", "level": 1},
    {"word": "Wednesday", "translation": "среда", "level": 1},
    {"word": "Thursday", "translation": "четверг", "level": 1},
    {"word": "Friday", "translation": "пятница", "level": 1},
    {"word": "Saturday", "translation": "суббота", "level": 1},
    {"word": "Sunday", "translation": "воскресенье", "level": 1},
    {"word": "spring", "translation": "весна", "level": 1},
    {"word": "summer", "translation": "лето", "level": 1},
    {"word": "autumn", "translation": "осень", "level": 1},
    {"word": "winter", "translation": "зима", "level": 1},
    {"word": "now", "translation": "сейчас", "level": 1},
    {"word": "then", "translation": "тогда", "level": 1},
    {"word": "always", "translation": "всегда", "level": 1},
    {"word": "never", "translation": "никогда", "level": 1},
    {"word": "often", "translation": "часто", "level": 1},
    {"word": "sometimes", "translation": "иногда", "level": 1},
    {"word": "usually", "translation": "обычно", "level": 1},
    {"word": "soon", "translation": "скоро", "level": 1},
    {"word": "early", "translation": "рано", "level": 1},
    {"word": "late", "translation": "поздно", "level": 1},
    {"word": "again", "translation": "снова", "level": 1},
    {"word": "here", "translation": "здесь", "level": 1},
    {"word": "there", "translation": "там", "level": 1},
    {"word": "everywhere", "translation": "везде", "level": 1},
    {"word": "nowhere", "translation": "нигде", "level": 1}
]

# Уровень 2 - 300 слов
level_2_words = [
    # Более сложные глаголы (80 слов)
    {"word": "achieve", "translation": "достигать", "level": 2},
    {"word": "admire", "translation": "восхищаться", "level": 2},
    {"word": "affect", "translation": "влиять", "level": 2},
    {"word": "agree", "translation": "соглашаться", "level": 2},
    {"word": "allow", "translation": "позволять", "level": 2},
    {"word": "appear", "translation": "появляться", "level": 2},
    {"word": "apply", "translation": "применять", "level": 2},
    {"word": "argue", "translation": "спорить", "level": 2},
    {"word": "arrange", "translation": "организовывать", "level": 2},
    {"word": "arrive", "translation": "прибывать", "level": 2},
    {"word": "assume", "translation": "предполагать", "level": 2},
    {"word": "avoid", "translation": "избегать", "level": 2},
    {"word": "become", "translation": "становиться", "level": 2},
    {"word": "believe", "translation": "верить", "level": 2},
    {"word": "belong", "translation": "принадлежать", "level": 2},
    {"word": "build", "translation": "строить", "level": 2},
    {"word": "buy", "translation": "покупать", "level": 2},
    {"word": "care", "translation": "заботиться", "level": 2},
    {"word": "carry", "translation": "нести", "level": 2},
    {"word": "catch", "translation": "ловить", "level": 2},
    {"word": "cause", "translation": "вызывать", "level": 2},
    {"word": "choose", "translation": "выбирать", "level": 2},
    {"word": "claim", "translation": "утверждать", "level": 2},
    {"word": "collect", "translation": "собирать", "level": 2},
    {"word": "compare", "translation": "сравнивать", "level": 2},
    {"word": "concern", "translation": "касаться", "level": 2},
    {"word": "confirm", "translation": "подтверждать", "level": 2},
    {"word": "connect", "translation": "соединять", "level": 2},
    {"word": "consider", "translation": "рассматривать", "level": 2},
    {"word": "consist", "translation": "состоять", "level": 2},
    {"word": "contain", "translation": "содержать", "level": 2},
    {"word": "continue", "translation": "продолжать", "level": 2},
    {"word": "contribute", "translation": "способствовать", "level": 2},
    {"word": "control", "translation": "контролировать", "level": 2},
    {"word": "convince", "translation": "убеждать", "level": 2},
    {"word": "cook", "translation": "готовить", "level": 2},
    {"word": "cost", "translation": "стоить", "level": 2},
    {"word": "count", "translation": "считать", "level": 2},
    {"word": "cover", "translation": "покрывать", "level": 2},
    {"word": "create", "translation": "создавать", "level": 2},
    {"word": "cut", "translation": "резать", "level": 2},
    {"word": "deal", "translation": "иметь дело", "level": 2},
    {"word": "decide", "translation": "решать", "level": 2},
    {"word": "declare", "translation": "объявлять", "level": 2},
    {"word": "decrease", "translation": "уменьшать", "level": 2},
    {"word": "deliver", "translation": "доставлять", "level": 2},
    {"word": "demand", "translation": "требовать", "level": 2},
    {"word": "deny", "translation": "отрицать", "level": 2},
    {"word": "depend", "translation": "зависеть", "level": 2},
    {"word": "describe", "translation": "описывать", "level": 2},
    {"word": "design", "translation": "проектировать", "level": 2},
    {"word": "destroy", "translation": "уничтожать", "level": 2},
    {"word": "determine", "translation": "определять", "level": 2},
    {"word": "develop", "translation": "развивать", "level": 2},
    {"word": "discover", "translation": "открывать", "level": 2},
    {"word": "discuss", "translation": "обсуждать", "level": 2},
    {"word": "divide", "translation": "делить", "level": 2},
    {"word": "draw", "translation": "рисовать", "level": 2},
    {"word": "dream", "translation": "мечтать", "level": 2},
    {"word": "drive", "translation": "водить", "level": 2},
    {"word": "drop", "translation": "бросать", "level": 2},
    {"word": "earn", "translation": "зарабатывать", "level": 2},
    {"word": "educate", "translation": "обучать", "level": 2},
    {"word": "encourage", "translation": "поощрять", "level": 2},
    {"word": "enjoy", "translation": "наслаждаться", "level": 2},
    {"word": "establish", "translation": "устанавливать", "level": 2},
    {"word": "estimate", "translation": "оценивать", "level": 2},
    {"word": "examine", "translation": "исследовать", "level": 2},
    {"word": "exist", "translation": "существовать", "level": 2},
    {"word": "expand", "translation": "расширять", "level": 2},
    {"word": "expect", "translation": "ожидать", "level": 2},
    {"word": "explain", "translation": "объяснять", "level": 2},
    {"word": "explore", "translation": "исследовать", "level": 2},
    {"word": "express", "translation": "выражать", "level": 2},
    {"word": "extend", "translation": "расширять", "level": 2},
    {"word": "face", "translation": "сталкиваться", "level": 2},
    {"word": "fail", "translation": "терпеть неудачу", "level": 2},
    {"word": "fall", "translation": "падать", "level": 2},
    {"word": "fear", "translation": "бояться", "level": 2},
    {"word": "feed", "translation": "кормить", "level": 2},
    {"word": "fight", "translation": "бороться", "level": 2},
    {"word": "fill", "translation": "заполнять", "level": 2},
    {"word": "fit", "translation": "подходить", "level": 2},
    
    # Абстрактные понятия (60 слов)
    {"word": "freedom", "translation": "свобода", "level": 2},
    {"word": "happiness", "translation": "счастье", "level": 2},
    {"word": "knowledge", "translation": "знание", "level": 2},
    {"word": "beauty", "translation": "красота", "level": 2},
    {"word": "truth", "translation": "правда", "level": 2},
    {"word": "justice", "translation": "справедливость", "level": 2},
    {"word": "courage", "translation": "мужество", "level": 2},
    {"word": "wisdom", "translation": "мудрость", "level": 2},
    {"word": "success", "translation": "успех", "level": 2},
    {"word": "failure", "translation": "неудача", "level": 2},
    {"word": "love", "translation": "любовь", "level": 2},
    {"word": "hate", "translation": "ненависть", "level": 2},
    {"word": "hope", "translation": "надежда", "level": 2},
    {"word": "fear", "translation": "страх", "level": 2},
    {"word": "anger", "translation": "гнев", "level": 2},
    {"word": "peace", "translation": "мир", "level": 2},
    {"word": "war", "translation": "война", "level": 2},
    {"word": "life", "translation": "жизнь", "level": 2},
    {"word": "death", "translation": "смерть", "level": 2},
    {"word": "time", "translation": "время", "level": 2},
    {"word": "space", "translation": "пространство", "level": 2},
    {"word": "energy", "translation": "энергия", "level": 2},
    {"word": "power", "translation": "сила", "level": 2},
    {"word": "money", "translation": "деньги", "level": 2},
    {"word": "health", "translation": "здоровье", "level": 2},
    {"word": "education", "translation": "образование", "level": 2},
    {"word": "culture", "translation": "культура", "level": 2},
    {"word": "society", "translation": "общество", "level": 2},
    {"word": "history", "translation": "история", "level": 2},
    {"word": "art", "translation": "искусство", "level": 2},
    {"word": "music", "translation": "музыка", "level": 2},
    {"word": "science", "translation": "наука", "level": 2},
    {"word": "technology", "translation": "технология", "level": 2},
    {"word": "nature", "translation": "природа", "level": 2},
    {"word": "environment", "translation": "окружающая среда", "level": 2},
    {"word": "development", "translation": "развитие", "level": 2},
    {"word": "change", "translation": "изменение", "level": 2},
    {"word": "progress", "translation": "прогресс", "level": 2},
    {"word": "problem", "translation": "проблема", "level": 2},
    {"word": "solution", "translation": "решение", "level": 2},
    {"word": "idea", "translation": "идея", "level": 2},
    {"word": "thought", "translation": "мысль", "level": 2},
    {"word": "feeling", "translation": "чувство", "level": 2},
    {"word": "emotion", "translation": "эмоция", "level": 2},
    {"word": "experience", "translation": "опыт", "level": 2},
    {"word": "memory", "translation": "память", "level": 2},
    {"word": "dream", "translation": "мечта", "level": 2},
    {"word": "goal", "translation": "цель", "level": 2},
    {"word": "plan", "translation": "план", "level": 2},
    {"word": "project", "translation": "проект", "level": 2},
    {"word": "system", "translation": "система", "level": 2},
    {"word": "process", "translation": "процесс", "level": 2},
    {"word": "method", "translation": "метод", "level": 2},
    {"word": "way", "translation": "способ", "level": 2},
    {"word": "result", "translation": "результат", "level": 2},
    {"word": "effect", "translation": "эффект", "level": 2},
    {"word": "cause", "translation": "причина", "level": 2},
    {"word": "reason", "translation": "причина", "level": 2},
    
    # Профессии и работа (50 слов)
    {"word": "engineer", "translation": "инженер", "level": 2},
    {"word": "lawyer", "translation": "юрист", "level": 2},
    {"word": "doctor", "translation": "врач", "level": 2},
    {"word": "teacher", "translation": "учитель", "level": 2},
    {"word": "manager", "translation": "менеджер", "level": 2},
    {"word": "director", "translation": "директор", "level": 2},
    {"word": "artist", "translation": "художник", "level": 2},
    {"word": "musician", "translation": "музыкант", "level": 2},
    {"word": "scientist", "translation": "ученый", "level": 2},
    {"word": "writer", "translation": "писатель", "level": 2},
    {"word": "journalist", "translation": "журналист", "level": 2},
    {"word": "actor", "translation": "актер", "level": 2},
    {"word": "actress", "translation": "актриса", "level": 2},
    {"word": "designer", "translation": "дизайнер", "level": 2},
    {"word": "architect", "translation": "архитектор", "level": 2},
    {"word": "nurse", "translation": "медсестра", "level": 2},
    {"word": "policeman", "translation": "полицейский", "level": 2},
    {"word": "firefighter", "translation": "пожарный", "level": 2},
    {"word": "soldier", "translation": "солдат", "level": 2},
    {"word": "pilot", "translation": "пилот", "level": 2},
    {"word": "driver", "translation": "водитель", "level": 2},
    {"word": "cook", "translation": "повар", "level": 2},
    {"word": "waiter", "translation": "официант", "level": 2},
    {"word": "waitress", "translation": "официантка", "level": 2},
    {"word": "secretary", "translation": "секретарь", "level": 2},
    {"word": "accountant", "translation": "бухгалтер", "level": 2},
    {"word": "banker", "translation": "банкир", "level": 2},
    {"word": "businessman", "translation": "бизнесмен", "level": 2},
    {"word": "entrepreneur", "translation": "предприниматель", "level": 2},
    {"word": "farmer", "translation": "фермер", "level": 2},
    {"word": "fisherman", "translation": "рыбак", "level": 2},
    {"word": "miner", "translation": "шахтер", "level": 2},
    {"word": "builder", "translation": "строитель", "level": 2},
    {"word": "carpenter", "translation": "плотник", "level": 2},
    {"word": "plumber", "translation": "водопроводчик", "level": 2},
    {"word": "electrician", "translation": "электрик", "level": 2},
    {"word": "mechanic", "translation": "механик", "level": 2},
    {"word": "technician", "translation": "техник", "level": 2},
    {"word": "programmer", "translation": "программист", "level": 2},
    {"word": "analyst", "translation": "аналитик", "level": 2},
    {"word": "consultant", "translation": "консультант", "level": 2},
    {"word": "advisor", "translation": "советник", "level": 2},
    {"word": "assistant", "translation": "помощник", "level": 2},
    {"word": "representative", "translation": "представитель", "level": 2},
    {"word": "agent", "translation": "агент", "level": 2},
    {"word": "officer", "translation": "офицер", "level": 2},
    {"word": "official", "translation": "чиновник", "level": 2},
    {"word": "president", "translation": "президент", "level": 2},
    {"word": "prime minister", "translation": "премьер-министр", "level": 2},
    
    # Образование и наука (50 слов)
    {"word": "education", "translation": "образование", "level": 2},
    {"word": "science", "translation": "наука", "level": 2},
    {"word": "research", "translation": "исследование", "level": 2},
    {"word": "experiment", "translation": "эксперимент", "level": 2},
    {"word": "theory", "translation": "теория", "level": 2},
    {"word": "method", "translation": "метод", "level": 2},
    {"word": "analysis", "translation": "анализ", "level": 2},
    {"word": "discovery", "translation": "открытие", "level": 2},
    {"word": "technology", "translation": "технология", "level": 2},
    {"word": "innovation", "translation": "инновация", "level": 2},
    {"word": "invention", "translation": "изобретение", "level": 2},
    {"word": "development", "translation": "развитие", "level": 2},
    {"word": "progress", "translation": "прогресс", "level": 2},
    {"word": "knowledge", "translation": "знание", "level": 2},
    {"word": "information", "translation": "информация", "level": 2},
    {"word": "data", "translation": "данные", "level": 2},
    {"word": "fact", "translation": "факт", "level": 2},
    {"word": "evidence", "translation": "доказательство", "level": 2},
    {"word": "proof", "translation": "подтверждение", "level": 2},
    {"word": "result", "translation": "результат", "level": 2},
    {"word": "conclusion", "translation": "заключение", "level": 2},
    {"word": "hypothesis", "translation": "гипотеза", "level": 2},
    {"word": "principle", "translation": "принцип", "level": 2},
    {"word": "law", "translation": "закон", "level": 2},
    {"word": "rule", "translation": "правило", "level": 2},
    {"word": "formula", "translation": "формула", "level": 2},
    {"word": "equation", "translation": "уравнение", "level": 2},
    {"word": "variable", "translation": "переменная", "level": 2},
    {"word": "constant", "translation": "константа", "level": 2},
    {"word": "parameter", "translation": "параметр", "level": 2},
    {"word": "function", "translation": "функция", "level": 2},
    {"word": "system", "translation": "система", "level": 2},
    {"word": "structure", "translation": "структура", "level": 2},
    {"word": "model", "translation": "модель", "level": 2},
    {"word": "pattern", "translation": "шаблон", "level": 2},
    {"word": "process", "translation": "процесс", "level": 2},
    {"word": "procedure", "translation": "процедура", "level": 2},
    {"word": "technique", "translation": "техника", "level": 2},
    {"word": "skill", "translation": "навык", "level": 2},
    {"word": "ability", "translation": "способность", "level": 2},
    {"word": "talent", "translation": "талант", "level": 2},
    {"word": "intelligence", "translation": "интеллект", "level": 2},
    {"word": "wisdom", "translation": "мудрость", "level": 2},
    {"word": "understanding", "translation": "понимание", "level": 2},
    {"word": "comprehension", "translation": "понимание", "level": 2},
    {"word": "learning", "translation": "обучение", "level": 2},
    {"word": "teaching", "translation": "преподавание", "level": 2},
    {"word": "training", "translation": "тренировка", "level": 2},
    {"word": "practice", "translation": "практика", "level": 2},
    
    # Чувства и эмоции (60 слов)
    {"word": "excited", "translation": "взволнованный", "level": 2},
    {"word": "anxious", "translation": "тревожный", "level": 2},
    {"word": "confident", "translation": "уверенный", "level": 2},
    {"word": "proud", "translation": "гордый", "level": 2},
    {"word": "grateful", "translation": "благодарный", "level": 2},
    {"word": "disappointed", "translation": "разочарованный", "level": 2},
    {"word": "frustrated", "translation": "расстроенный", "level": 2},
    {"word": "enthusiastic", "translation": "восторженный", "level": 2},
    {"word": "curious", "translation": "любопытный", "level": 2},
    {"word": "optimistic", "translation": "оптимистичный", "level": 2},
    {"word": "pessimistic", "translation": "пессимистичный", "level": 2},
    {"word": "calm", "translation": "спокойный", "level": 2},
    {"word": "nervous", "translation": "нервный", "level": 2},
    {"word": "worried", "translation": "обеспокоенный", "level": 2},
    {"word": "scared", "translation": "испуганный", "level": 2},
    {"word": "afraid", "translation": "испуганный", "level": 2},
    {"word": "terrified", "translation": "ужасно испуганный", "level": 2},
    {"word": "shocked", "translation": "шокированный", "level": 2},
    {"word": "surprised", "translation": "удивленный", "level": 2},
    {"word": "amazed", "translation": "пораженный", "level": 2},
    {"word": "impressed", "translation": "впечатленный", "level": 2},
    {"word": "pleased", "translation": "довольный", "level": 2},
    {"word": "satisfied", "translation": "удовлетворенный", "level": 2},
    {"word": "content", "translation": "довольный", "level": 2},
    {"word": "happy", "translation": "счастливый", "level": 2},
    {"word": "joyful", "translation": "радостный", "level": 2},
    {"word": "delighted", "translation": "восхищенный", "level": 2},
    {"word": "ecstatic", "translation": "в восторге", "level": 2},
    {"word": "sad", "translation": "грустный", "level": 2},
    {"word": "unhappy", "translation": "несчастный", "level": 2},
    {"word": "miserable", "translation": "несчастный", "level": 2},
    {"word": "depressed", "translation": "подавленный", "level": 2},
    {"word": "lonely", "translation": "одинокий", "level": 2},
    {"word": "bored", "translation": "скучающий", "level": 2},
    {"word": "tired", "translation": "уставший", "level": 2},
    {"word": "exhausted", "translation": "измученный", "level": 2},
    {"word": "sleepy", "translation": "сонный", "level": 2},
    {"word": "hungry", "translation": "голодный", "level": 2},
    {"word": "thirsty", "translation": "жаждущий", "level": 2},
    {"word": "sick", "translation": "больной", "level": 2},
    {"word": "ill", "translation": "больной", "level": 2},
    {"word": "healthy", "translation": "здоровый", "level": 2},
    {"word": "strong", "translation": "сильный", "level": 2},
    {"word": "weak", "translation": "слабый", "level": 2},
    {"word": "brave", "translation": "храбрый", "level": 2},
    {"word": "cowardly", "translation": "трусливый", "level": 2},
    {"word": "honest", "translation": "честный", "level": 2},
    {"word": "dishonest", "translation": "нечестный", "level": 2},
    {"word": "kind", "translation": "добрый", "level": 2},
    {"word": "cruel", "translation": "жестокий", "level": 2},
    {"word": "generous", "translation": "щедрый", "level": 2},
    {"word": "selfish", "translation": "эгоистичный", "level": 2},
    {"word": "polite", "translation": "вежливый", "level": 2},
    {"word": "rude", "translation": "грубый", "level": 2},
    {"word": "friendly", "translation": "дружелюбный", "level": 2},
    {"word": "unfriendly", "translation": "недружелюбный", "level": 2},
    {"word": "patient", "translation": "терпеливый", "level": 2},
    {"word": "impatient", "translation": "нетерпеливый", "level": 2}
]

# Уровень 3 - 250 слов
level_3_words = [
    # Академическая лексика (80 слов)
    {"word": "comprehensive", "translation": "всесторонний", "level": 3},
    {"word": "contemporary", "translation": "современный", "level": 3},
    {"word": "significant", "translation": "значительный", "level": 3},
    {"word": "fundamental", "translation": "фундаментальный", "level": 3},
    {"word": "complex", "translation": "сложный", "level": 3},
    {"word": "sophisticated", "translation": "изощренный", "level": 3},
    {"word": "ambiguous", "translation": "двусмысленный", "level": 3},
    {"word": "coherent", "translation": "связный", "level": 3},
    {"word": "compatible", "translation": "совместимый", "level": 3},
    {"word": "complementary", "translation": "дополнительный", "level": 3},
    {"word": "comprehensive", "translation": "всеобъемлющий", "level": 3},
    {"word": "conceptual", "translation": "концептуальный", "level": 3},
    {"word": "conclusive", "translation": "окончательный", "level": 3},
    {"word": "concurrent", "translation": "параллельный", "level": 3},
    {"word": "conditional", "translation": "условный", "level": 3},
    {"word": "consecutive", "translation": "последовательный", "level": 3},
    {"word": "considerable", "translation": "значительный", "level": 3},
    {"word": "consistent", "translation": "последовательный", "level": 3},
    {"word": "conspicuous", "translation": "заметный", "level": 3},
    {"word": "constitutional", "translation": "конституционный", "level": 3},
    {"word": "controversial", "translation": "спорный", "level": 3},
    {"word": "conventional", "translation": "традиционный", "level": 3},
    {"word": "crucial", "translation": "решающий", "level": 3},
    {"word": "cumulative", "translation": "накопительный", "level": 3},
    {"word": "decisive", "translation": "решающий", "level": 3},
    {"word": "definitive", "translation": "определенный", "level": 3},
    {"word": "deliberate", "translation": "преднамеренный", "level": 3},
    {"word": "democratic", "translation": "демократический", "level": 3},
    {"word": "desirable", "translation": "желательный", "level": 3},
    {"word": "detrimental", "translation": "вредный", "level": 3},
    {"word": "developmental", "translation": "развивающий", "level": 3},
    {"word": "diagnostic", "translation": "диагностический", "level": 3},
    {"word": "differential", "translation": "дифференциальный", "level": 3},
    {"word": "disciplinary", "translation": "дисциплинарный", "level": 3},
    {"word": "discretionary", "translation": "дискреционный", "level": 3},
    {"word": "discriminatory", "translation": "дискриминационный", "level": 3},
    {"word": "disproportionate", "translation": "непропорциональный", "level": 3},
    {"word": "distinctive", "translation": "отличительный", "level": 3},
    {"word": "diverse", "translation": "разнообразный", "level": 3},
    {"word": "dynamic", "translation": "динамичный", "level": 3},
    {"word": "ecological", "translation": "экологический", "level": 3},
    {"word": "economic", "translation": "экономический", "level": 3},
    {"word": "effective", "translation": "эффективный", "level": 3},
    {"word": "efficient", "translation": "эффективный", "level": 3},
    {"word": "elaborate", "translation": "тщательно разработанный", "level": 3},
    {"word": "elementary", "translation": "элементарный", "level": 3},
    {"word": "eligible", "translation": "имеющий право", "level": 3},
    {"word": "emergent", "translation": "возникающий", "level": 3},
    {"word": "empirical", "translation": "эмпирический", "level": 3},
    {"word": "enormous", "translation": "огромный", "level": 3},
    {"word": "environmental", "translation": "экологический", "level": 3},
    {"word": "epidemiological", "translation": "эпидемиологический", "level": 3},
    {"word": "equitable", "translation": "справедливый", "level": 3},
    {"word": "equivalent", "translation": "эквивалентный", "level": 3},
    {"word": "essential", "translation": "существенный", "level": 3},
    {"word": "established", "translation": "установленный", "level": 3},
    {"word": "ethical", "translation": "этический", "level": 3},
    {"word": "ethnic", "translation": "этнический", "level": 3},
    {"word": "evaluative", "translation": "оценочный", "level": 3},
    {"word": "eventual", "translation": "окончательный", "level": 3},
    {"word": "evident", "translation": "очевидный", "level": 3},
    {"word": "evolutionary", "translation": "эволюционный", "level": 3},
    {"word": "excessive", "translation": "чрезмерный", "level": 3},
    {"word": "exclusive", "translation": "эксклюзивный", "level": 3},
    {"word": "executive", "translation": "исполнительный", "level": 3},
    {"word": "exhaustive", "translation": "исчерпывающий", "level": 3},
    {"word": "experimental", "translation": "экспериментальный", "level": 3},
    {"word": "explicit", "translation": "явный", "level": 3},
    {"word": "exploratory", "translation": "исследовательский", "level": 3},
    {"word": "extensive", "translation": "обширный", "level": 3},
    {"word": "external", "translation": "внешний", "level": 3},
    {"word": "extreme", "translation": "экстремальный", "level": 3},
    {"word": "facilitative", "translation": "способствующий", "level": 3},
    {"word": "factual", "translation": "фактический", "level": 3},
    {"word": "familiar", "translation": "знакомый", "level": 3},
    {"word": "feasible", "translation": "осуществимый", "level": 3},
    {"word": "federal", "translation": "федеральный", "level": 3},
    {"word": "flexible", "translation": "гибкий", "level": 3},
    {"word": "formal", "translation": "формальный", "level": 3},
    {"word": "functional", "translation": "функциональный", "level": 3},
    
    # Бизнес и экономика (60 слов)
    {"word": "entrepreneur", "translation": "предприниматель", "level": 3},
    {"word": "investment", "translation": "инвестиция", "level": 3},
    {"word": "strategy", "translation": "стратегия", "level": 3},
    {"word": "negotiation", "translation": "переговоры", "level": 3},
    {"word": "partnership", "translation": "партнерство", "level": 3},
    {"word": "competitor", "translation": "конкурент", "level": 3},
    {"word": "revenue", "translation": "доход", "level": 3},
    {"word": "expenditure", "translation": "расход", "level": 3},
    {"word": "bankruptcy", "translation": "банкротство", "level": 3},
    {"word": "merger", "translation": "слияние", "level": 3},
    {"word": "acquisition", "translation": "приобретение", "level": 3},
    {"word": "corporation", "translation": "корпорация", "level": 3},
    {"word": "subsidiary", "translation": "дочерняя компания", "level": 3},
    {"word": "franchise", "translation": "франшиза", "level": 3},
    {"word": "franchisee", "translation": "франчайзи", "level": 3},
    {"word": "franchisor", "translation": "франчайзер", "level": 3},
    {"word": "stakeholder", "translation": "заинтересованная сторона", "level": 3},
    {"word": "shareholder", "translation": "акционер", "level": 3},
    {"word": "dividend", "translation": "дивиденд", "level": 3},
    {"word": "equity", "translation": "акционерный капитал", "level": 3},
    {"word": "debt", "translation": "долг", "level": 3},
    {"word": "leverage", "translation": "рычаг", "level": 3},
    {"word": "liquidity", "translation": "ликвидность", "level": 3},
    {"word": "solvency", "translation": "платежеспособность", "level": 3},
    {"word": "profitability", "translation": "рентабельность", "level": 3},
    {"word": "efficiency", "translation": "эффективность", "level": 3},
    {"word": "productivity", "translation": "производительность", "level": 3},
    {"word": "innovation", "translation": "инновация", "level": 3},
    {"word": "creativity", "translation": "креативность", "level": 3},
    {"word": "leadership", "translation": "лидерство", "level": 3},
    {"word": "management", "translation": "управление", "level": 3},
    {"word": "administration", "translation": "администрация", "level": 3},
    {"word": "organization", "translation": "организация", "level": 3},
    {"word": "structure", "translation": "структура", "level": 3},
    {"word": "hierarchy", "translation": "иерархия", "level": 3},
    {"word": "bureaucracy", "translation": "бюрократия", "level": 3},
    {"word": "autonomy", "translation": "автономия", "level": 3},
    {"word": "authority", "translation": "власть", "level": 3},
    {"word": "responsibility", "translation": "ответственность", "level": 3},
    {"word": "accountability", "translation": "подотчетность", "level": 3},
    {"word": "transparency", "translation": "прозрачность", "level": 3},
    {"word": "governance", "translation": "управление", "level": 3},
    {"word": "compliance", "translation": "соответствие", "level": 3},
    {"word": "regulation", "translation": "регулирование", "level": 3},
    {"word": "legislation", "translation": "законодательство", "level": 3},
    {"word": "policy", "translation": "политика", "level": 3},
    {"word": "procedure", "translation": "процедура", "level": 3},
    {"word": "protocol", "translation": "протокол", "level": 3},
    {"word": "standard", "translation": "стандарт", "level": 3},
    {"word": "benchmark", "translation": "ориентир", "level": 3},
    {"word": "metric", "translation": "метрика", "level": 3},
    {"word": "indicator", "translation": "индикатор", "level": 3},
    {"word": "parameter", "translation": "параметр", "level": 3},
    {"word": "criterion", "translation": "критерий", "level": 3},
    {"word": "threshold", "translation": "порог", "level": 3},
    {"word": "milestone", "translation": "веха", "level": 3},
    {"word": "deadline", "translation": "крайний срок", "level": 3},
    {"word": "timeline", "translation": "график", "level": 3},
    {"word": "schedule", "translation": "расписание", "level": 3},
    
    # Психология и философия (60 слов)
    {"word": "consciousness", "translation": "сознание", "level": 3},
    {"word": "perception", "translation": "восприятие", "level": 3},
    {"word": "cognition", "translation": "познание", "level": 3},
    {"word": "introspection", "translation": "самоанализ", "level": 3},
    {"word": "empathy", "translation": "эмпатия", "level": 3},
    {"word": "resilience", "translation": "устойчивость", "level": 3},
    {"word": "mindfulness", "translation": "осознанность", "level": 3},
    {"word": "existential", "translation": "экзистенциальный", "level": 3},
    {"word": "phenomenon", "translation": "феномен", "level": 3},
    {"word": "paradigm", "translation": "парадигма", "level": 3},
    {"word": "epistemology", "translation": "эпистемология", "level": 3},
    {"word": "ontology", "translation": "онтология", "level": 3},
    {"word": "metaphysics", "translation": "метафизика", "level": 3},
    {"word": "ethics", "translation": "этика", "level": 3},
    {"word": "aesthetics", "translation": "эстетика", "level": 3},
    {"word": "logic", "translation": "логика", "level": 3},
    {"word": "rationality", "translation": "рациональность", "level": 3},
    {"word": "reasoning", "translation": "рассуждение", "level": 3},
    {"word": "inference", "translation": "умозаключение", "level": 3},
    {"word": "deduction", "translation": "дедукция", "level": 3},
    {"word": "induction", "translation": "индукция", "level": 3},
    {"word": "abduction", "translation": "абдукция", "level": 3},
    {"word": "syllogism", "translation": "силлогизм", "level": 3},
    {"word": "premise", "translation": "посылка", "level": 3},
    {"word": "conclusion", "translation": "заключение", "level": 3},
    {"word": "argument", "translation": "аргумент", "level": 3},
    {"word": "proposition", "translation": "предложение", "level": 3},
    {"word": "assertion", "translation": "утверждение", "level": 3},
    {"word": "claim", "translation": "утверждение", "level": 3},
    {"word": "thesis", "translation": "тезис", "level": 3},
    {"word": "antithesis", "translation": "антитезис", "level": 3},
    {"word": "synthesis", "translation": "синтез", "level": 3},
    {"word": "dialectic", "translation": "диалектика", "level": 3},
    {"word": "contradiction", "translation": "противоречие", "level": 3},
    {"word": "paradox", "translation": "парадокс", "level": 3},
    {"word": "dilemma", "translation": "дилемма", "level": 3},
    {"word": "conundrum", "translation": "головоломка", "level": 3},
    {"word": "enigma", "translation": "загадка", "level": 3},
    {"word": "mystery", "translation": "тайна", "level": 3},
    {"word": "ambiguity", "translation": "неоднозначность", "level": 3},
    {"word": "vagueness", "translation": "расплывчатость", "level": 3},
    {"word": "precision", "translation": "точность", "level": 3},
    {"word": "accuracy", "translation": "точность", "level": 3},
    {"word": "validity", "translation": "валидность", "level": 3},
    {"word": "reliability", "translation": "надежность", "level": 3},
    {"word": "objectivity", "translation": "объективность", "level": 3},
    {"word": "subjectivity", "translation": "субъективность", "level": 3},
    {"word": "relativism", "translation": "релятивизм", "level": 3},
    {"word": "absolutism", "translation": "абсолютизм", "level": 3},
    {"word": "skepticism", "translation": "скептицизм", "level": 3},
    {"word": "dogmatism", "translation": "догматизм", "level": 3},
    {"word": "pragmatism", "translation": "прагматизм", "level": 3},
    {"word": "idealism", "translation": "идеализм", "level": 3},
    {"word": "realism", "translation": "реализм", "level": 3},
    {"word": "materialism", "translation": "материализм", "level": 3},
    {"word": "dualism", "translation": "дуализм", "level": 3},
    {"word": "monism", "translation": "монизм", "level": 3},
    {"word": "pluralism", "translation": "плюрализм", "level": 3},
    {"word": "holism", "translation": "холизм", "level": 3},
    
    # Наука и технологии (50 слов)
    {"word": "algorithm", "translation": "алгоритм", "level": 3},
    {"word": "sustainable", "translation": "устойчивый", "level": 3},
    {"word": "renewable", "translation": "возобновляемый", "level": 3},
    {"word": "biodegradable", "translation": "биоразлагаемый", "level": 3},
    {"word": "nanotechnology", "translation": "нанотехнология", "level": 3},
    {"word": "biodiversity", "translation": "биоразнообразие", "level": 3},
    {"word": "cybersecurity", "translation": "кибербезопасность", "level": 3},
    {"word": "autonomous", "translation": "автономный", "level": 3},
    {"word": "virtual", "translation": "виртуальный", "level": 3},
    {"word": "quantum", "translation": "квантовый", "level": 3},
    {"word": "biotechnology", "translation": "биотехнология", "level": 3},
    {"word": "genetic", "translation": "генетический", "level": 3},
    {"word": "genomic", "translation": "геномный", "level": 3},
    {"word": "proteomic", "translation": "протеомный", "level": 3},
    {"word": "metabolomic", "translation": "метаболомный", "level": 3},
    {"word": "transcriptomic", "translation": "транскриптомный", "level": 3},
    {"word": "epigenetic", "translation": "эпигенетический", "level": 3},
    {"word": "pharmacogenomic", "translation": "фармакогеномный", "level": 3},
    {"word": "bioinformatic", "translation": "биоинформатический", "level": 3},
    {"word": "computational", "translation": "вычислительный", "level": 3},
    {"word": "algorithmic", "translation": "алгоритмический", "level": 3},
    {"word": "heuristic", "translation": "эвристический", "level": 3},
    {"word": "probabilistic", "translation": "вероятностный", "level": 3},
    {"word": "stochastic", "translation": "стохастический", "level": 3},
    {"word": "deterministic", "translation": "детерминистический", "level": 3},
    {"word": "chaotic", "translation": "хаотический", "level": 3},
    {"word": "fractal", "translation": "фрактальный", "level": 3},
    {"word": "holographic", "translation": "голографический", "level": 3},
    {"word": "photonic", "translation": "фотонный", "level": 3},
    {"word": "electronic", "translation": "электронный", "level": 3},
    {"word": "magnetic", "translation": "магнитный", "level": 3},
    {"word": "electromagnetic", "translation": "электромагнитный", "level": 3},
    {"word": "optical", "translation": "оптический", "level": 3},
    {"word": "acoustic", "translation": "акустический", "level": 3},
    {"word": "thermal", "translation": "тепловой", "level": 3},
    {"word": "thermodynamic", "translation": "термодинамический", "level": 3},
    {"word": "kinetic", "translation": "кинетический", "level": 3},
    {"word": "potential", "translation": "потенциальный", "level": 3},
    {"word": "mechanical", "translation": "механический", "level": 3},
    {"word": "electrical", "translation": "электрический", "level": 3},
    {"word": "chemical", "translation": "химический", "level": 3},
    {"word": "biological", "translation": "биологический", "level": 3},
    {"word": "ecological", "translation": "экологический", "level": 3},
    {"word": "environmental", "translation": "экологический", "level": 3},
    {"word": "geological", "translation": "геологический", "level": 3},
    {"word": "meteorological", "translation": "метеорологический", "level": 3},
    {"word": "astronomical", "translation": "астрономический", "level": 3},
    {"word": "cosmological", "translation": "космологический", "level": 3},
    {"word": "theoretical", "translation": "теоретический", "level": 3},
    {"word": "experimental", "translation": "экспериментальный", "level": 3}
]

# Уровень 4 - 150 слов
level_4_words = [
    # Высокоуровневая лексика (150 слов)
    {"word": "ubiquitous", "translation": "вездесущий", "level": 4},
    {"word": "paradoxical", "translation": "парадоксальный", "level": 4},
    {"word": "idiosyncratic", "translation": "идиосинкразический", "level": 4},
    {"word": "magnanimous", "translation": "великодушный", "level": 4},
    {"word": "perspicacious", "translation": "проницательный", "level": 4},
    {"word": "vicarious", "translation": "косвенный", "level": 4},
    {"word": "obfuscate", "translation": "запутывать", "level": 4},
    {"word": "equivocate", "translation": "уклоняться", "level": 4},
    {"word": "proliferate", "translation": "размножаться", "level": 4},
    {"word": "ameliorate", "translation": "улучшать", "level": 4},
    {"word": "exacerbate", "translation": "обострять", "level": 4},
    {"word": "mitigate", "translation": "смягчать", "level": 4},
    {"word": "aggregate", "translation": "совокупный", "level": 4},
    {"word": "convoluted", "translation": "запутанный", "level": 4},
    {"word": "labyrinthine", "translation": "лабиринтный", "level": 4},
    {"word": "sesquipedalian", "translation": "многосложный", "level": 4},
    {"word": "supercilious", "translation": "надменный", "level": 4},
    {"word": "vociferous", "translation": "шумный", "level": 4},
    {"word": "winsome", "translation": "очаровательный", "level": 4},
    {"word": "xenial", "translation": "гостеприимный", "level": 4},
    {"word": "yeomanly", "translation": "усердный", "level": 4},
    {"word": "zealous", "translation": "ревностный", "level": 4},
    {"word": "abstemious", "translation": "воздержанный", "level": 4},
    {"word": "bombastic", "translation": "напыщенный", "level": 4},
    {"word": "capricious", "translation": "капризный", "level": 4},
    {"word": "dilatory", "translation": "медлительный", "level": 4},
    {"word": "ebullient", "translation": "восторженный", "level": 4},
    {"word": "facetious", "translation": "шутливый", "level": 4},
    {"word": "garrulous", "translation": "болтливый", "level": 4},
    {"word": "histrionic", "translation": "театральный", "level": 4},
    {"word": "iconoclastic", "translation": "иконоборческий", "level": 4},
    {"word": "jocular", "translation": "шутливый", "level": 4},
    {"word": "kaleidoscopic", "translation": "калейдоскопический", "level": 4},
    {"word": "loquacious", "translation": "разговорчивый", "level": 4},
    {"word": "mellifluous", "translation": "мелодичный", "level": 4},
    {"word": "nefarious", "translation": "зловещий", "level": 4},
    {"word": "obstreperous", "translation": "непокорный", "level": 4},
    {"word": "perfidious", "translation": "вероломный", "level": 4},
    {"word": "quixotic", "translation": "рыцарский", "level": 4},
    {"word": "redolent", "translation": "ароматный", "level": 4},
    {"word": "sagacious", "translation": "мудрый", "level": 4},
    {"word": "taciturn", "translation": "молчаливый", "level": 4},
    {"word": "ubiquitous", "translation": "вездесущий", "level": 4},
    {"word": "venerable", "translation": "почтенный", "level": 4},
    {"word": "wistful", "translation": "тоскливый", "level": 4},
    {"word": "xenophobic", "translation": "ксенофобский", "level": 4},
    {"word": "yielding", "translation": "уступчивый", "level": 4},
    {"word": "zealous", "translation": "усердный", "level": 4},
    {"word": "aberrant", "translation": "отклоняющийся", "level": 4},
    {"word": "benevolent", "translation": "благожелательный", "level": 4},
    {"word": "cacophonous", "translation": "дисгармоничный", "level": 4},
    {"word": "dearth", "translation": "недостаток", "level": 4},
    {"word": "ebullient", "translation": "восторженный", "level": 4},
    {"word": "fastidious", "translation": "привередливый", "level": 4},
    {"word": "gregarious", "translation": "общительный", "level": 4},
    {"word": "harangue", "translation": "страстная речь", "level": 4},
    {"word": "idiosyncratic", "translation": "своеобразный", "level": 4},
    {"word": "juxtaposition", "translation": "сопоставление", "level": 4},
    {"word": "kowtow", "translation": "раболепствовать", "level": 4},
    {"word": "laconic", "translation": "лаконичный", "level": 4},
    {"word": "malleable", "translation": "податливый", "level": 4},
    {"word": "neophyte", "translation": "новичок", "level": 4},
    {"word": "obfuscate", "translation": "затемнять", "level": 4},
    {"word": "panacea", "translation": "панацея", "level": 4},
    {"word": "quandary", "translation": "затруднительное положение", "level": 4},
    {"word": "recapitulate", "translation": "пересказывать", "level": 4},
    {"word": "sanguine", "translation": "оптимистичный", "level": 4},
    {"word": "tractable", "translation": "покладистый", "level": 4},
    {"word": "ubiquitous", "translation": "повсеместный", "level": 4},
    {"word": "vacillate", "translation": "колебаться", "level": 4},
    {"word": "wane", "translation": "убывать", "level": 4},
    {"word": "xenial", "translation": "дружелюбный", "level": 4},
    {"word": "yoke", "translation": "ярмо", "level": 4},
    {"word": "zealot", "translation": "фанатик", "level": 4},
    {"word": "abnegation", "translation": "отречение", "level": 4},
    {"word": "blandishment", "translation": "лесть", "level": 4},
    {"word": "cajole", "translation": "убеждать", "level": 4},
    {"word": "dearth", "translation": "нехватка", "level": 4},
    {"word": "ebullient", "translation": "оживленный", "level": 4},
    {"word": "facile", "translation": "поверхностный", "level": 4},
    {"word": "gambol", "translation": "резвиться", "level": 4},
    {"word": "halcyon", "translation": "безмятежный", "level": 4},
    {"word": "iconoclast", "translation": "ниспровергатель", "level": 4},
    {"word": "jettison", "translation": "выбрасывать", "level": 4},
    {"word": "kudos", "translation": "похвала", "level": 4},
    {"word": "languid", "translation": "вялый", "level": 4},
    {"word": "mendacious", "translation": "лживый", "level": 4},
    {"word": "nadir", "translation": "низшая точка", "level": 4},
    {"word": "obsequious", "translation": "раболепный", "level": 4},
    {"word": "paragon", "translation": "образец", "level": 4},
    {"word": "quaff", "translation": "пить большими глотками", "level": 4},
    {"word": "raconteur", "translation": "рассказчик", "level": 4},
    {"word": "sagacious", "translation": "проницательный", "level": 4},
    {"word": "taciturn", "translation": "немногословный", "level": 4},
    {"word": "ubiquitous", "translation": "повсеместный", "level": 4},
    {"word": "vacuous", "translation": "пустой", "level": 4},
    {"word": "wheedle", "translation": "убеждать", "level": 4},
    {"word": "xenophobia", "translation": "ксенофобия", "level": 4},
    {"word": "yen", "translation": "сильное желание", "level": 4},
    {"word": "zealous", "translation": "рьяный", "level": 4},
    {"word": "abrogate", "translation": "отменять", "level": 4},
    {"word": "bucolic", "translation": "пасторальный", "level": 4},
    {"word": "capricious", "translation": "непостоянный", "level": 4},
    {"word": "dearth", "translation": "скудость", "level": 4},
    {"word": "ebullient", "translation": "воодушевленный", "level": 4},
    {"word": "fecund", "translation": "плодовитый", "level": 4},
    {"word": "garrulous", "translation": "словоохотливый", "level": 4},
    {"word": "hapless", "translation": "несчастный", "level": 4},
    {"word": "ineffable", "translation": "невыразимый", "level": 4},
    {"word": "jocular", "translation": "шутливый", "level": 4},
    {"word": "knavery", "translation": "мошенничество", "level": 4},
    {"word": "laconic", "translation": "краткий", "level": 4},
    {"word": "mellifluous", "translation": "сладкозвучный", "level": 4},
    {"word": "nebulous", "translation": "туманный", "level": 4},
    {"word": "obstreperous", "translation": "буйный", "level": 4},
    {"word": "perfidious", "translation": "предательский", "level": 4},
    {"word": "quixotic", "translation": "донкихотский", "level": 4},
    {"word": "redolent", "translation": "напоминающий", "level": 4},
    {"word": "sagacious", "translation": "мудрый", "level": 4},
    {"word": "taciturn", "translation": "неразговорчивый", "level": 4},
    {"word": "ubiquitous", "translation": "вездесущий", "level": 4},
    {"word": "vacillate", "translation": "нерешительно колебаться", "level": 4},
    {"word": "wanton", "translation": "беспричинный", "level": 4},
    {"word": "xenial", "translation": "гостеприимный", "level": 4},
    {"word": "yearn", "translation": "страстно желать", "level": 4},
    {"word": "zeal", "translation": "рвение", "level": 4}
]

# Предложения по уровням
level_1_sentences = [
    {"sentence": "I like apples.", "translation": "Мне нравятся яблоки.", "level": 1},
    {"sentence": "She reads books.", "translation": "Она читает книги.", "level": 1},
    {"sentence": "We go to school.", "translation": "Мы ходим в школу.", "level": 1},
    {"sentence": "He plays football.", "translation": "Он играет в футбол.", "level": 1},
    {"sentence": "They live in Moscow.", "translation": "Они живут в Москве.", "level": 1},
    {"sentence": "I have a cat.", "translation": "У меня есть кот.", "level": 1},
    {"sentence": "She is a teacher.", "translation": "Она учитель.", "level": 1},
    {"sentence": "We are students.", "translation": "Мы студенты.", "level": 1},
    {"sentence": "He works every day.", "translation": "Он работает каждый день.", "level": 1},
    {"sentence": "They speak English.", "translation": "Они говорят по-английски.", "level": 1},
    {"sentence": "I drink coffee in the morning.", "translation": "Я пью кофе утром.", "level": 1},
    {"sentence": "She watches TV in the evening.", "translation": "Она смотрит телевизор вечером.", "level": 1},
    {"sentence": "We eat dinner at 7 PM.", "translation": "Мы ужинаем в 7 вечера.", "level": 1},
    {"sentence": "He studies at university.", "translation": "Он учится в университете.", "level": 1},
    {"sentence": "They travel in summer.", "translation": "Они путешествуют летом.", "level": 1},
    {"sentence": "The sun is shining.", "translation": "Солнце светит.", "level": 1},
    {"sentence": "Birds are singing.", "translation": "Птицы поют.", "level": 1},
    {"sentence": "Children are playing.", "translation": "Дети играют.", "level": 1},
    {"sentence": "My mother cooks dinner.", "translation": "Моя мама готовит ужин.", "level": 1},
    {"sentence": "Our family has a car.", "translation": "У нашей семьи есть машина.", "level": 1},
    {"sentence": "I want to learn English.", "translation": "Я хочу выучить английский.", "level": 1},
    {"sentence": "She can play the piano.", "translation": "Она умеет играть на пианино.", "level": 1},
    {"sentence": "We must finish our homework.", "translation": "Мы должны закончить домашнюю работу.", "level": 1},
    {"sentence": "He should visit the doctor.", "translation": "Ему следует посетить врача.", "level": 1},
    {"sentence": "They might come tomorrow.", "translation": "Они, возможно, придут завтра.", "level": 1},
    {"sentence": "I need to buy some bread.", "translation": "Мне нужно купить хлеб.", "level": 1},
    {"sentence": "She loves her job.", "translation": "Она любит свою работу.", "level": 1},
    {"sentence": "We enjoy watching movies.", "translation": "Мы любим смотреть фильмы.", "level": 1},
    {"sentence": "He hates waking up early.", "translation": "Он ненавидит рано вставать.", "level": 1},
    {"sentence": "They prefer tea to coffee.", "translation": "Они предпочитают чай кофе.", "level": 1}
]

level_2_sentences = [
    {"sentence": "I have been learning English for two years.", "translation": "Я учу английский уже два года.", "level": 2},
    {"sentence": "She will have finished her work by tomorrow.", "translation": "Она закончит свою работу к завтрашнему дню.", "level": 2},
    {"sentence": "If I had more time, I would travel more.", "translation": "Если бы у меня было больше времени, я бы больше путешествовал.", "level": 2},
    {"sentence": "The book that I'm reading is very interesting.", "translation": "Книга, которую я читаю, очень интересная.", "level": 2},
    {"sentence": "Despite the rain, we decided to go for a walk.", "translation": "Несмотря на дождь, мы решили пойти на прогулку.", "level": 2},
    {"sentence": "He suggested that we should meet later.", "translation": "Он предложил, чтобы мы встретились позже.", "level": 2},
    {"sentence": "I'm looking forward to seeing you again.", "translation": "Я с нетерпением жду новой встречи с тобой.", "level": 2},
    {"sentence": "She used to play piano when she was younger.", "translation": "Она раньше играла на пианино, когда была моложе.", "level": 2},
    {"sentence": "We might go to the cinema if we have time.", "translation": "Мы, возможно, пойдем в кино, если у нас будет время.", "level": 2},
    {"sentence": "He can speak three languages fluently.", "translation": "Он может говорить на трех языках свободно.", "level": 2},
    {"sentence": "The company is considering expanding to new markets.", "translation": "Компания рассматривает возможность расширения на новые рынки.", "level": 2},
    {"sentence": "Having completed the project, they celebrated their success.", "translation": "Завершив проект, они отпраздновали свой успех.", "level": 2},
    {"sentence": "Not only did she finish first, but she also broke the record.", "translation": "Она не только финишировала первой, но и побила рекорд.", "level": 2},
    {"sentence": "The more I learn, the more I realize how much I don't know.", "translation": "Чем больше я узнаю, тем больше понимаю, как много я не знаю.", "level": 2},
    {"sentence": "It's high time we started taking climate change seriously.", "translation": "Самое время начать серьезно относиться к изменению климата.", "level": 2},
    {"sentence": "Were I in your shoes, I would consider all options carefully.", "translation": "Будь я на твоем месте, я бы тщательно рассмотрел все варианты.", "level": 2},
    {"sentence": "The government is expected to announce new policies soon.", "translation": "Ожидается, что правительство скоро объявит о новых политиках.", "level": 2},
    {"sentence": "Having lived abroad for years, she was fluent in several languages.", "translation": "Прожив за границей годами, она свободно говорила на нескольких языках.", "level": 2},
    {"sentence": "The team worked around the clock to meet the deadline.", "translation": "Команда работала круглосуточно, чтобы уложиться в срок.", "level": 2},
    {"sentence": "It goes without saying that education is important for everyone.", "translation": "Само собой разумеется, что образование важно для всех.", "level": 2},
    {"sentence": "The research findings were both surprising and significant.", "translation": "Результаты исследования были и удивительными, и значительными.", "level": 2},
    {"sentence": "We'd better leave now if we want to avoid the traffic.", "translation": "Нам лучше уехать сейчас, если мы хотим избежать пробок.", "level": 2},
    {"sentence": "The concert was called off due to bad weather conditions.", "translation": "Концерт был отменен из-за плохих погодных условий.", "level": 2},
    {"sentence": "She made up her mind to pursue a career in medicine.", "translation": "Она решила сделать карьеру в медицине.", "level": 2},
    {"sentence": "The company takes pride in its commitment to quality.", "translation": "Компания гордится своей приверженностью качеству.", "level": 2},
    {"sentence": "It's worth noting that the situation has improved significantly.", "translation": "Стоит отметить, что ситуация значительно улучшилась.", "level": 2},
    {"sentence": "The new policy will come into effect next month.", "translation": "Новая политика вступит в силу в следующем месяце.", "level": 2},
    {"sentence": "We need to take into account all possible consequences.", "translation": "Нам нужно принять во внимание все возможные последствия.", "level": 2},
    {"sentence": "The project turned out to be more challenging than expected.", "translation": "Проект оказался более сложным, чем ожидалось.", "level": 2},
    {"sentence": "There's no point in arguing about it anymore.", "translation": "Нет смысла больше спорить об этом.", "level": 2}
]

level_3_sentences = [
    {"sentence": "Had I known about the traffic, I would have left earlier.", "translation": "Знай я о пробках, я бы уехал раньше.", "level": 3},
    {"sentence": "Not only does she speak French, but she also writes poetry in it.", "translation": "Она не только говорит по-французски, но и пишет на нем стихи.", "level": 3},
    {"sentence": "The project, which had been delayed for months, was finally completed.", "translation": "Проект, который откладывался месяцами, был наконец завершен.", "level": 3},
    {"sentence": "Were I in your position, I would consider all options carefully.", "translation": "Окажись я на твоем месте, я бы тщательно рассмотрел все варианты.", "level": 3},
    {"sentence": "Despite having studied for hours, he found the exam challenging.", "translation": "Несмотря на то что он учился часами, экзамен показался ему сложным.", "level": 3},
    {"sentence": "The company is looking for candidates who are proficient in multiple programming languages.", "translation": "Компания ищет кандидатов, владеющих несколькими языками программирования.", "level": 3},
    {"sentence": "Having traveled extensively, she had many interesting stories to share.", "translation": "Много путешествуя, у нее было много интересных историй.", "level": 3},
    {"sentence": "The proposal was rejected on the grounds that it was not feasible.", "translation": "Предложение было отклонено на том основании, что оно не было выполнимым.", "level": 3},
    {"sentence": "It is imperative that all documents be submitted by the deadline.", "translation": "Крайне важно, чтобы все документы были поданы к сроку.", "level": 3},
    {"sentence": "The research findings, while preliminary, suggest a promising direction.", "translation": "Результаты исследования, хотя и предварительные, указывают на перспективное направление.", "level": 3},
    {"sentence": "Were the circumstances different, we might have reached an agreement.", "translation": "Будь обстоятельства другими, мы, возможно, достигли бы соглашения.", "level": 3},
    {"sentence": "The committee's recommendation is that further investigation be conducted.", "translation": "Рекомендация комитета заключается в проведении дальнейшего расследования.", "level": 3},
    {"sentence": "Not until he had reviewed all the evidence did he form an opinion.", "translation": "Только после того как он изучил все доказательства, он сформировал мнение.", "level": 3},
    {"sentence": "The complexity of the issue necessitates a multidisciplinary approach.", "translation": "Сложность вопроса требует междисциплинарного подхода.", "level": 3},
    {"sentence": "Had they been aware of the risks, they would have taken precautions.", "translation": "Знай они о рисках, они бы приняли меры предосторожности.", "level": 3},
    {"sentence": "The implementation of the new system is contingent upon several factors.", "translation": "Внедрение новой системы зависит от нескольких факторов.", "level": 3},
    {"sentence": "It is of paramount importance that confidentiality be maintained.", "translation": "Крайне важно, чтобы конфиденциальность была сохранена.", "level": 3},
    {"sentence": "The study's methodology was rigorously reviewed by independent experts.", "translation": "Методология исследования была тщательно проверена независимыми экспертами.", "level": 3},
    {"sentence": "Were the budget approved, we could commence the project immediately.", "translation": "Будь бюджет утвержден, мы могли бы начать проект немедленно.", "level": 3},
    {"sentence": "The agreement is subject to ratification by the board of directors.", "translation": "Соглашение подлежит ратификации советом директоров.", "level": 3},
    {"sentence": "It is incumbent upon us to ensure the safety of all participants.", "translation": "На нас лежит обязанность обеспечить безопасность всех участников.", "level": 3},
    {"sentence": "The proposal, albeit innovative, requires further refinement.", "translation": "Предложение, хотя и инновационное, требует дальнейшей доработки.", "level": 3},
    {"sentence": "Were the data more comprehensive, our conclusions would be stronger.", "translation": "Будь данные более полными, наши выводы были бы более убедительными.", "level": 3},
    {"sentence": "The committee's findings are indicative of systemic issues.", "translation": "Выводы комитета свидетельствуют о системных проблемах.", "level": 3},
    {"sentence": "It is conceivable that new evidence may emerge in the future.", "translation": "Вполне возможно, что в будущем появятся новые доказательства.", "level": 3}
]

level_4_sentences = [
    {"sentence": "Notwithstanding the considerable obstacles that lay ahead, the team remained undaunted in their pursuit of innovation.", "translation": "Несмотря на значительные препятствия, которые лежали впереди, команда оставалась неустрашимой в своем стремлении к инновациям.", "level": 4},
    {"sentence": "Had the committee been apprised of the potential ramifications earlier, they might have adopted a more cautious approach.", "translation": "Знай комитет о потенциальных последствиях раньше, они, возможно, приняли бы более осторожный подход.", "level": 4},
    {"sentence": "The intricacy of the problem necessitated a multifaceted approach that took into account various interdependent factors.", "translation": "Сложность проблемы требовала многогранного подхода, учитывающего различные взаимозависимые факторы.", "level": 4},
    {"sentence": "Were one to extrapolate from the current trends, it would become apparent that significant changes are imminent.", "translation": "Если бы кто-то экстраполировал из текущих тенденций, стало бы очевидно, что значительные изменения неизбежны.", "level": 4},
    {"sentence": "The proposition, albeit theoretically sound, proved to be impracticable when subjected to real-world constraints.", "translation": "Предложение, хотя и теоретически обоснованное, оказалось неосуществимым при применении реальных ограничений.", "level": 4},
    {"sentence": "His perspicacious analysis of the market dynamics enabled him to anticipate shifts that eluded less observant investors.", "translation": "Его проницательный анализ рыночной динамики позволил ему предвидеть изменения, которые ускользнули от менее наблюдательных инвесторов.", "level": 4},
    {"sentence": "The confluence of economic, social, and technological factors created a perfect storm that precipitated the crisis.", "translation": "Слияние экономических, социальных и технологических факторов создало идеальный шторм, который спровоцировал кризис.", "level": 4},
    {"sentence": "Had the intricacies of the situation been fully comprehended from the outset, a different strategy might have been employed.", "translation": "Знай сложности ситуации с самого начала, возможно, была бы применена другая стратегия.", "level": 4},
    {"sentence": "The quintessence of their argument resided in the fundamental principles of justice and equity.", "translation": "Квинтэссенция их аргумента заключалась в фундаментальных принципах справедливости и равенства.", "level": 4},
    {"sentence": "Notwithstanding the ostensibly insurmountable challenges, they persevered with unwavering determination.", "translation": "Несмотря на казалось бы непреодолимые трудности, они persevered с непоколебимой решимостью.", "level": 4},
    {"sentence": "The epistemological underpinnings of their methodology were subjected to rigorous philosophical scrutiny.", "translation": "Эпистемологические основы их методологии подверглись тщательному философскому анализу.", "level": 4},
    {"sentence": "Had the ramifications of their actions been properly anticipated, the catastrophic consequences might have been averted.", "translation": "Знай последствия их действий были должным образом предвидены, катастрофические результаты, возможно, были бы предотвращены.", "level": 4},
    {"sentence": "The multifarious aspects of the dilemma precluded any facile solution.", "translation": "Многообразные аспекты дилеммы исключали какое-либо простое решение.", "level": 4},
    {"sentence": "Their perspicacity in discerning underlying patterns enabled them to maintain a competitive advantage.", "translation": "Их проницательность в распознавании скрытых закономерностей позволила им сохранить конкурентное преимущество.", "level": 4},
    {"sentence": "The ontological assumptions implicit in their framework warranted critical examination.", "translation": "Онтологические предположения, неявно присутствующие в их framework, требовали критического рассмотрения.", "level": 4}
]

def insert_initial_data():
    """Добавление начальных данных в базу"""
    connection = db.connect()
    cursor = connection.cursor()
    
    # Очищаем таблицы перед добавлением
    cursor.execute("DELETE FROM words")
    cursor.execute("DELETE FROM sentences")
    
    # Вставляем слова
    all_words = level_1_words + level_2_words + level_3_words + level_4_words
    for word_data in all_words:
        cursor.execute(
            "INSERT INTO words (word, translation, level) VALUES (%s, %s, %s)",
            (word_data['word'], word_data['translation'], word_data['level'])
        )
    
    # Вставляем предложения
    all_sentences = level_1_sentences + level_2_sentences + level_3_sentences + level_4_sentences
    for sentence_data in all_sentences:
        cursor.execute(
            "INSERT INTO sentences (sentence, translation, level) VALUES (%s, %s, %s)",
            (sentence_data['sentence'], sentence_data['translation'], sentence_data['level'])
        )
    
    connection.commit()
    cursor.close()
    connection.close()
    print(f"✅ Добавлено {len(all_words)} слов и {len(all_sentences)} предложений!")

if __name__ == '__main__':
    insert_initial_data()
